<div class="menu">
    <div class="menu__column">
        <h4><a href="https://swagnavi.com/contact"><?php echo __('Contact Us')?></a></h4>
        <ul>
            <li>&nbsp;<?php echo __('2270 W Chenango Ave, Unit 100')?></li>
            <li>&nbsp;Littleton, CO 80120</li>
            <li>&nbsp;<?php echo __('TEL: 303-733-3366')?></a></li>
            <li>&nbsp;<?php echo __('EMAIL: orders@customembellishment.com')?></li>
        </ul>
    </div>
    <div class="menu__column">
        <h4><?php echo __('Other Embroidery Needs?')?></h4>
        <ul>
            <li><a href="https://www.instagram.com/customembellishment/" target="_blank"><img style="width:50px;" src="https://www.swagnavi.com/media/wysiwyg/instagram.png" ></li>
            <li><a href="https://www.customembellishment.net" target="_blank"><?php echo __('Visit Us')?></a></li>
        </ul>
    </div> -->
</div>
